import { Component, Input} from '@angular/core';
import {FacebookInitialiser} from './fb.initialiser';

/*
 * This is a facebook share button auto-generated by facebook share plugin
 * source url is an input property defined by the parent component
 */
@Component({
	selector: 'facebook-share-btn',
	template: `
	<iframe class="e2e-iframe-trusted-src"
			[src]="iframe_url() | safe"
			width="73" height="28" style="border:none;overflow:hidden" scrolling="no"
			frameborder="0" allowTransparency="true"></iframe>`,
	// providers: [FacebookInitialiser]
})

export class FacebookShareButton {

	constructor(private fb: FacebookInitialiser) {
	}
	@Input() url: string;

	iframe_url(): string {
		return 'https://www.facebook.com/plugins/share_button.php?href=' + encodeURIComponent(this.url) + '&layout=button&size=large&mobile_iframe=false&appId=194305457670086&width=73&height=28';
	}
}
