import {Component, Input} from '@angular/core';
import {FacebookInitialiser} from './fb.initialiser';

declare var FB: any;
/*
 * This is a facebook share button auto-generated by facebook share plugin
 * source url is an input property defined by the parent component
 */
@Component({
	selector: 'facebook-share-btn',
	template: `
    <i class="material-icons" (click)="share($event)" style="font-size:36px;">share</i>
  `
})

export class FacebookShareButton {

	constructor(private fb_init: FacebookInitialiser) {
	}

	@Input() url: string;

	share($event) {
		$event.stopPropagation();
		let params = {
			method: 'share',
			href: this.url
		};

		FB.ui(params, function (response) {
			// do something on response?
		});
	}
}
