import { Component, Input} from '@angular/core';
import {FacebookInitialiser} from './fb.initialiser';

/*
 * This is a facebook share button auto-generated by facebook share plugin
 * source url is an input property defined by the parent component
 */
@Component({
	selector: 'facebook-share-btn',
	template: `<i class="material-icons" style="font-size:36px;">share</i>`
})

export class FacebookShareButton {

	constructor(private fb: FacebookInitialiser) {
	}
	@Input() url: string;

	share_url(): string {
		return 'https://www.facebook.com/plugins/share_button.php?href=' + encodeURIComponent(this.url) + '&layout=button&size=large&mobile_iframe=false&appId=194305457670086&width=73&height=28';
	}
}
